# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'React', :path => '../node_modules/react-native', :subspecs => [

  'RCTImage' # <- Add this line
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


target 'CryptoSorter' do
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

 pod 'RNSVG', :path => '../node_modules/react-native-svg'


#  target 'CryptoSorterTests' do
#     inherit! :search_paths
#       Pods for testing
#   end

end




